# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-21 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import treemenus.models


class Migration(migrations.Migration):

    dependencies = [
        ('treemenus', '0005_auto_20181204_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, help_text='PNG, JPG, GIF only.', null=True, upload_to=treemenus.models.SlugifyUpload('upload/menu'), verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='svg',
            field=models.FileField(blank=True, help_text='svg has higher priority over the image', null=True, upload_to=treemenus.models.SlugifyUpload('upload/menu'), verbose_name='svg'),
        ),
    ]
