# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-21 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import treemenus.models


class Migration(migrations.Migration):

    dependencies = [
        ('treemenus', '0006_auto_20190621_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='named_url',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='svg',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=treemenus.models.SlugifyUpload('upload/menu'), verbose_name='image'),
        ),
    ]
